//! VCD correctness verification tests.
//!
//! Validates that WAL-parsed signal values match the known patterns
//! generated by gen_vcd_pyvcd.py.
//!
//! Generated signal patterns:
//!   counter:   value = timestamp_idx % 2^32
//!   strobe:    value = (timestamp_idx / 1000) % 2
//!   data_bus:  value = (timestamp_idx >> 2) ^ 0xDEADBEEFABCD1234
//!   sigN:      value = (timestamp_idx + N) % 2

use std::path::Path;
use wal_rust::trace::{Trace, VcdTrace, ScalarValue};

fn compute_counter(t: usize) -> i64 {
    (t as i64) % (1i64 << 32)
}

fn compute_strobe_bit(t: usize) -> u8 {
    if (t / 1000) % 2 == 0 { b'0' } else { b'1' }
}

fn compute_sig_bit(t: usize, i: usize) -> u8 {
    if (t + i) % 2 == 0 { b'0' } else { b'1' }
}

/// Find signal by name hint
fn find_signal(trace: &VcdTrace, name_hint: &str) -> Option<String> {
    trace.signals().into_iter().find(|s| {
        s == name_hint || s.contains(name_hint)
    })
}

#[test]
fn test_vcd_pyvcd_load_signals() {
    let path = Path::new("test_data/test_pyvcd_100M.vcd");
    if !path.exists() {
        eprintln!("Skipping: test_pyvcd_100M.vcd not found");
        return;
    }
    let trace = VcdTrace::load(path, "test".to_string()).unwrap();
    let signals = trace.signals();
    assert!(!signals.is_empty(), "Should have at least one signal");
    assert!(signals.len() >= 53, "Expected >= 53 signals, got {}", signals.len());
    let max = trace.max_index();
    assert!(max > 0, "Should have timestamps");
    eprintln!("pyvcd VCD: {} signals, max_index={}", signals.len(), max);
}

#[test]
fn test_vcd_pyvcd_verify_counter() {
    let path = Path::new("test_data/test_pyvcd_100M.vcd");
    if !path.exists() {
        eprintln!("Skipping: test_pyvcd_100M.vcd not found");
        return;
    }
    let trace = VcdTrace::load(path, "test".to_string()).unwrap();
    let sig = find_signal(&trace, "counter").expect("counter signal not found");
    let max = trace.max_index();
    let step = (max - 1) / 20;
    let mut errors = 0;
    for i in 0..=20 {
        let idx = 1 + (i * step).min(max - 1);
        match trace.signal_value(&sig, idx) {
            Ok(ScalarValue::Vector(ref v)) => {
                let actual = v.iter().fold(0i64, |acc, &b| (acc << 1) | ((b - b'0') as i64));
                let expected = compute_counter(idx);
                if actual != expected {
                    eprintln!("MISMATCH counter at idx={}: expected {}, got {}", idx, expected, actual);
                    errors += 1;
                }
            }
            other => {
                eprintln!("Unexpected value type for counter at {}: {:?}", idx, other);
                errors += 1;
            }
        }
    }
    assert_eq!(errors, 0, "Counter value mismatches: {}", errors);
    eprintln!("Counter verification: PASSED (20 samples)");
}

#[test]
fn test_vcd_pyvcd_verify_strobe() {
    let path = Path::new("test_data/test_pyvcd_100M.vcd");
    if !path.exists() {
        eprintln!("Skipping: test_pyvcd_100M.vcd not found");
        return;
    }
    let trace = VcdTrace::load(path, "test".to_string()).unwrap();
    let sig = find_signal(&trace, "strobe").expect("strobe signal not found");
    let max = trace.max_index();
    let mut errors = 0;
    for idx in [0usize, 999, 1000, 1001, 1999, 2000] {
        let idx = idx.min(max);
        match trace.signal_value(&sig, idx) {
            Ok(ScalarValue::Bit(b)) => {
                let expected = compute_strobe_bit(idx);
                if b != expected {
                    eprintln!("MISMATCH strobe at idx={}: expected {:?}, got {:?}",
                              idx, expected as char, b as char);
                    errors += 1;
                }
            }
            other => {
                eprintln!("Unexpected value for strobe at {}: {:?}", idx, other);
                errors += 1;
            }
        }
    }
    assert_eq!(errors, 0, "Strobe value mismatches: {}", errors);
    eprintln!("Strobe verification: PASSED");
}

#[test]
fn test_vcd_pyvcd_verify_checkerboard() {
    let path = Path::new("test_data/test_pyvcd_100M.vcd");
    if !path.exists() {
        eprintln!("Skipping: test_pyvcd_100M.vcd not found");
        return;
    }
    let trace = VcdTrace::load(path, "test".to_string()).unwrap();
    let sig = find_signal(&trace, "sig10").expect("sig10 not found");
    let sig_idx: usize = 10;
    let max = trace.max_index();
    let step = (max - 1) / 20;
    let mut errors = 0;
    for i in 0..=20 {
        let idx = 1 + (i * step).min(max - 1);
        match trace.signal_value(&sig, idx) {
            Ok(ScalarValue::Bit(b)) => {
                let expected = compute_sig_bit(idx, sig_idx);
                if b != expected {
                    eprintln!("MISMATCH {} at idx={}: expected {:?}, got {:?}",
                              sig, idx, expected as char, b as char);
                    errors += 1;
                }
            }
            other => {
                eprintln!("Unexpected value for {} at {}: {:?}", sig, idx, other);
                errors += 1;
            }
        }
    }
    assert_eq!(errors, 0, "Checkerboard mismatches: {}", errors);
    eprintln!("Checkerboard verification: PASSED ({} signal, 20 samples)", sig);
}

// ========================================================================
// Diverse VCD test cases (generated by Icarus Verilog and Python)
// ========================================================================

fn try_load_vcd(name: &str) -> Option<wal_rust::trace::VcdTrace> {
    let path = std::path::Path::new("test_data").join(name);
    if !path.exists() {
        eprintln!("SKIP: {} not found", name);
        return None;
    }
    match wal_rust::trace::VcdTrace::load(&path, name.to_string()) {
        Ok(t) => Some(t),
        Err(e) => {
            panic!("Failed to load {}: {}", name, e);
        }
    }
}

#[test]
fn test_vcd_icarus_counter() {
    let trace = match try_load_vcd("counter.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 2, "counter: expected >=2 signals, got {}", sigs.len());
    let max_idx = trace.max_index();
    assert!(max_idx > 0, "counter: should have timestamps");
    eprintln!("counter.vcd: {} signals, max_idx={}", sigs.len(), max_idx);
    if let Some(count_sig) = sigs.iter().find(|s| s.contains("count")) {
        let val = trace.signal_value(count_sig, max_idx).unwrap();
        eprintln!("  {} @ idx={}: {:?}", count_sig, max_idx, val);
    }
}

#[test]
fn test_vcd_icarus_hierarchy() {
    let trace = match try_load_vcd("hierarchy.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 4, "hierarchy: expected >=4 signals, got {}", sigs.len());
    let has_hier = sigs.iter().any(|s| s.contains('.'));
    assert!(has_hier, "hierarchy: expected dotted signal names, got: {:?}", sigs);
    eprintln!("hierarchy.vcd: {} signals, hierarchical={}", sigs.len(), has_hier);
}

#[test]
fn test_vcd_icarus_types() {
    let trace = match try_load_vcd("types.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 5, "types: expected >=5 signals, got {}", sigs.len());
    eprintln!("types.vcd: {} signals: {:?}", sigs.len(), sigs);
}

#[test]
fn test_vcd_icarus_many_signals() {
    let trace = match try_load_vcd("many_signals.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 100, "many_signals: expected >=100 signals, got {}", sigs.len());
    eprintln!("many_signals.vcd: {} signals", sigs.len());
}

#[test]
fn test_vcd_icarus_long() {
    let trace = match try_load_vcd("long.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    let max_idx = trace.max_index();
    assert!(max_idx >= 2000, "long.vcd: expected >=2000 timestamps, got {}", max_idx);
    eprintln!("long.vcd: {} signals, max_idx={}", sigs.len(), max_idx);
}

#[test]
fn test_vcd_edge_single_signal() {
    let trace = match try_load_vcd("edge_single_signal.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 1, "edge_single_signal: expected >=1 signal, got {}", sigs.len());
    eprintln!("edge_single_signal.vcd: 1 signal OK");
}

#[test]
fn test_vcd_edge_no_signals() {
    let _trace = match try_load_vcd("edge_no_signals.vcd") { Some(t) => t, None => return };
    let sigs = _trace.signals();
    assert_eq!(sigs.len(), 0, "expected 0 signals");
    eprintln!("edge_no_signals.vcd: 0 signals OK");
}

#[test]
fn test_vcd_edge_long_names() {
    let trace = match try_load_vcd("edge_long_names.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 1, "expected >=1 signal");
    let longest = sigs.iter().max_by_key(|s| s.len()).unwrap();
    assert!(longest.len() > 100, "expected signal name >100 chars, got {}", longest.len());
    eprintln!("edge_long_names.vcd: longest name = {} chars", longest.len());
}

#[test]
fn test_vcd_edge_all_value_types() {
    let trace = match try_load_vcd("edge_all_value_types.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 2, "expected >=2 signal types, got {}", sigs.len());
    let max_idx = trace.max_index();
    assert!(max_idx > 0, "expected timestamps");
    eprintln!("edge_all_value_types.vcd: {} signals, max_idx={}", sigs.len(), max_idx);
}

#[test]
fn test_vcd_edge_real_values() {
    let trace = match try_load_vcd("edge_real_values.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 1, "expected real signal");
    eprintln!("edge_real_values.vcd: {} signals", sigs.len());
}

#[test]
fn test_vcd_edge_large_vectors() {
    let trace = match try_load_vcd("edge_large_vectors.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 2, "expected >=2 wide signals, got {}", sigs.len());
    eprintln!("edge_large_vectors.vcd: {} signals", sigs.len());
    if let Some(big) = sigs.iter().find(|s| s.contains("big")) {
        let val = trace.signal_value(big, 0).unwrap();
        eprintln!("  {} @ idx=0: {:?}", big, val);
    }
}

#[test]
fn test_vcd_edge_multi_scope() {
    let trace = match try_load_vcd("edge_multi_scope.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 3, "expected >=3 signals across scopes, got {}", sigs.len());
    let has_dots = sigs.iter().any(|s| s.contains('.'));
    eprintln!("edge_multi_scope.vcd: {} signals, has_dots={}", sigs.len(), has_dots);
}

#[test]
fn test_vcd_edge_empty_time() {
    let trace = match try_load_vcd("edge_empty_time.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    let max_idx = trace.max_index();
    assert!(max_idx > 0, "expected timestamps even with empty sections");
    eprintln!("edge_empty_time.vcd: {} signals, max_idx={}", sigs.len(), max_idx);
}

#[test]
fn test_vcd_large_flat() {
    let trace = match try_load_vcd("large_flat.vcd") { Some(t) => t, None => return };
    let sigs = trace.signals();
    assert!(sigs.len() >= 1000, "large_flat: expected >=1000 signals, got {}", sigs.len());
    let max_idx = trace.max_index();
    assert!(max_idx >= 99, "large_flat: expected >=99 timestamps, got {}", max_idx);
    eprintln!("large_flat.vcd: {} signals, max_idx={}", sigs.len(), max_idx);
}
