//! VCD correctness verification tests.
//!
//! Validates that WAL-parsed signal values match the known patterns
//! generated by gen_vcd_pyvcd.py.
//!
//! Generated signal patterns:
//!   counter:   value = timestamp_idx % 2^32
//!   strobe:    value = (timestamp_idx / 1000) % 2
//!   data_bus:  value = (timestamp_idx >> 2) ^ 0xDEADBEEFABCD1234
//!   sigN:      value = (timestamp_idx + N) % 2

use std::path::Path;
use wal_rust::trace::{Trace, VcdTrace, ScalarValue};

fn compute_counter(t: usize) -> i64 {
    (t as i64) % (1i64 << 32)
}

fn compute_strobe_bit(t: usize) -> u8 {
    if (t / 1000) % 2 == 0 { b'0' } else { b'1' }
}

fn compute_sig_bit(t: usize, i: usize) -> u8 {
    if (t + i) % 2 == 0 { b'0' } else { b'1' }
}

/// Find signal by name hint
fn find_signal(trace: &VcdTrace, name_hint: &str) -> Option<String> {
    trace.signals().into_iter().find(|s| {
        s == name_hint || s.contains(name_hint)
    })
}

#[test]
fn test_vcd_pyvcd_load_signals() {
    let path = Path::new("test_data/test_pyvcd_100M.vcd");
    if !path.exists() {
        eprintln!("Skipping: test_pyvcd_100M.vcd not found");
        return;
    }
    let trace = VcdTrace::load(path, "test".to_string()).unwrap();
    let signals = trace.signals();
    assert!(!signals.is_empty(), "Should have at least one signal");
    assert!(signals.len() >= 53, "Expected >= 53 signals, got {}", signals.len());
    let max = trace.max_index();
    assert!(max > 0, "Should have timestamps");
    eprintln!("pyvcd VCD: {} signals, max_index={}", signals.len(), max);
}

#[test]
fn test_vcd_pyvcd_verify_counter() {
    let path = Path::new("test_data/test_pyvcd_100M.vcd");
    if !path.exists() {
        eprintln!("Skipping: test_pyvcd_100M.vcd not found");
        return;
    }
    let trace = VcdTrace::load(path, "test".to_string()).unwrap();
    let sig = find_signal(&trace, "counter").expect("counter signal not found");
    let max = trace.max_index();
    let step = (max - 1) / 20;
    let mut errors = 0;
    for i in 0..=20 {
        let idx = 1 + (i * step).min(max - 1);
        match trace.signal_value(&sig, idx) {
            Ok(ScalarValue::Vector(ref v)) => {
                let actual = v.iter().fold(0i64, |acc, &b| (acc << 1) | ((b - b'0') as i64));
                let expected = compute_counter(idx);
                if actual != expected {
                    eprintln!("MISMATCH counter at idx={}: expected {}, got {}", idx, expected, actual);
                    errors += 1;
                }
            }
            other => {
                eprintln!("Unexpected value type for counter at {}: {:?}", idx, other);
                errors += 1;
            }
        }
    }
    assert_eq!(errors, 0, "Counter value mismatches: {}", errors);
    eprintln!("Counter verification: PASSED (20 samples)");
}

#[test]
fn test_vcd_pyvcd_verify_strobe() {
    let path = Path::new("test_data/test_pyvcd_100M.vcd");
    if !path.exists() {
        eprintln!("Skipping: test_pyvcd_100M.vcd not found");
        return;
    }
    let trace = VcdTrace::load(path, "test".to_string()).unwrap();
    let sig = find_signal(&trace, "strobe").expect("strobe signal not found");
    let max = trace.max_index();
    let mut errors = 0;
    for idx in [0usize, 999, 1000, 1001, 1999, 2000] {
        let idx = idx.min(max);
        match trace.signal_value(&sig, idx) {
            Ok(ScalarValue::Bit(b)) => {
                let expected = compute_strobe_bit(idx);
                if b != expected {
                    eprintln!("MISMATCH strobe at idx={}: expected {:?}, got {:?}",
                              idx, expected as char, b as char);
                    errors += 1;
                }
            }
            other => {
                eprintln!("Unexpected value for strobe at {}: {:?}", idx, other);
                errors += 1;
            }
        }
    }
    assert_eq!(errors, 0, "Strobe value mismatches: {}", errors);
    eprintln!("Strobe verification: PASSED");
}

#[test]
fn test_vcd_pyvcd_verify_checkerboard() {
    let path = Path::new("test_data/test_pyvcd_100M.vcd");
    if !path.exists() {
        eprintln!("Skipping: test_pyvcd_100M.vcd not found");
        return;
    }
    let trace = VcdTrace::load(path, "test".to_string()).unwrap();
    let sig = find_signal(&trace, "sig10").expect("sig10 not found");
    let sig_idx: usize = 10;
    let max = trace.max_index();
    let step = (max - 1) / 20;
    let mut errors = 0;
    for i in 0..=20 {
        let idx = 1 + (i * step).min(max - 1);
        match trace.signal_value(&sig, idx) {
            Ok(ScalarValue::Bit(b)) => {
                let expected = compute_sig_bit(idx, sig_idx);
                if b != expected {
                    eprintln!("MISMATCH {} at idx={}: expected {:?}, got {:?}",
                              sig, idx, expected as char, b as char);
                    errors += 1;
                }
            }
            other => {
                eprintln!("Unexpected value for {} at {}: {:?}", sig, idx, other);
                errors += 1;
            }
        }
    }
    assert_eq!(errors, 0, "Checkerboard mismatches: {}", errors);
    eprintln!("Checkerboard verification: PASSED ({} signal, 20 samples)", sig);
}
