#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 35
#define LARGE_STATE_COUNT 29
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_base_symbol = 1,
  anon_sym_AT = 2,
  anon_sym_SQUOTE = 3,
  anon_sym_BQUOTE = 4,
  anon_sym_COMMA = 5,
  anon_sym_COMMA_AT = 6,
  sym_whitespace = 7,
  sym__comment = 8,
  sym__line_comment = 9,
  sym_float = 10,
  sym_dec_int = 11,
  sym_bin_int = 12,
  sym_hex_int = 13,
  anon_sym_true = 14,
  anon_sym_false = 15,
  anon_sym_POUNDt = 16,
  anon_sym_POUNDf = 17,
  anon_sym_nil = 18,
  anon_sym_PLUS = 19,
  anon_sym_DASH = 20,
  anon_sym_STAR = 21,
  anon_sym_SLASH = 22,
  anon_sym_AMP_AMP = 23,
  anon_sym_PIPE_PIPE = 24,
  anon_sym_EQ = 25,
  anon_sym_BANG_EQ = 26,
  anon_sym_GT = 27,
  anon_sym_LT = 28,
  anon_sym_GT_EQ = 29,
  anon_sym_LT_EQ = 30,
  anon_sym_BANG = 31,
  anon_sym_STAR_STAR = 32,
  anon_sym_TILDE = 33,
  anon_sym_POUND = 34,
  sym_string = 35,
  anon_sym_LPAREN = 36,
  anon_sym_RPAREN = 37,
  anon_sym_LBRACK = 38,
  anon_sym_RBRACK = 39,
  anon_sym_LBRACE = 40,
  anon_sym_RBRACE = 41,
  sym_program = 42,
  sym_sexpr = 43,
  sym_timed_atom = 44,
  sym_quoted = 45,
  sym_quasiquoted = 46,
  sym_unquote = 47,
  sym_unquote_splice = 48,
  sym_atom = 49,
  sym_int = 50,
  sym_bool = 51,
  sym_operator = 52,
  sym_symbol = 53,
  sym_scoped_symbol = 54,
  sym_grouped_symbol = 55,
  sym_list = 56,
  sym_sexpr_list = 57,
  aux_sym_program_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_base_symbol] = "base_symbol",
  [anon_sym_AT] = "@",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_COMMA] = ",",
  [anon_sym_COMMA_AT] = ",@",
  [sym_whitespace] = "whitespace",
  [sym__comment] = "_comment",
  [sym__line_comment] = "_line_comment",
  [sym_float] = "float",
  [sym_dec_int] = "dec_int",
  [sym_bin_int] = "bin_int",
  [sym_hex_int] = "hex_int",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_POUNDt] = "#t",
  [anon_sym_POUNDf] = "#f",
  [anon_sym_nil] = "nil",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_TILDE] = "~",
  [anon_sym_POUND] = "#",
  [sym_string] = "string",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_program] = "program",
  [sym_sexpr] = "sexpr",
  [sym_timed_atom] = "timed_atom",
  [sym_quoted] = "quoted",
  [sym_quasiquoted] = "quasiquoted",
  [sym_unquote] = "unquote",
  [sym_unquote_splice] = "unquote_splice",
  [sym_atom] = "atom",
  [sym_int] = "int",
  [sym_bool] = "bool",
  [sym_operator] = "operator",
  [sym_symbol] = "symbol",
  [sym_scoped_symbol] = "scoped_symbol",
  [sym_grouped_symbol] = "grouped_symbol",
  [sym_list] = "list",
  [sym_sexpr_list] = "sexpr_list",
  [aux_sym_program_repeat1] = "program_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_base_symbol] = sym_base_symbol,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COMMA_AT] = anon_sym_COMMA_AT,
  [sym_whitespace] = sym_whitespace,
  [sym__comment] = sym__comment,
  [sym__line_comment] = sym__line_comment,
  [sym_float] = sym_float,
  [sym_dec_int] = sym_dec_int,
  [sym_bin_int] = sym_bin_int,
  [sym_hex_int] = sym_hex_int,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_POUNDt] = anon_sym_POUNDt,
  [anon_sym_POUNDf] = anon_sym_POUNDf,
  [anon_sym_nil] = anon_sym_nil,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_string] = sym_string,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_program] = sym_program,
  [sym_sexpr] = sym_sexpr,
  [sym_timed_atom] = sym_timed_atom,
  [sym_quoted] = sym_quoted,
  [sym_quasiquoted] = sym_quasiquoted,
  [sym_unquote] = sym_unquote,
  [sym_unquote_splice] = sym_unquote_splice,
  [sym_atom] = sym_atom,
  [sym_int] = sym_int,
  [sym_bool] = sym_bool,
  [sym_operator] = sym_operator,
  [sym_symbol] = sym_symbol,
  [sym_scoped_symbol] = sym_scoped_symbol,
  [sym_grouped_symbol] = sym_grouped_symbol,
  [sym_list] = sym_list,
  [sym_sexpr_list] = sym_sexpr_list,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_base_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym__line_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_dec_int] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_int] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nil] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_sexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_timed_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_quasiquoted] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote_splice] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_scoped_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_sexpr_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
};

static TSCharacterRange sym_base_symbol_character_set_1[] = {
  {'!', '!'}, {'$', '%'}, {'*', ':'}, {'<', '?'}, {'A', 'Z'}, {'\\', '\\'}, {'^', '_'}, {'a', 'z'},
  {'|', '|'}, {'~', '~'}, {0xa7, 0xa7},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 37,
        '"', 1,
        '#', 40,
        '&', 2,
        '\'', 10,
        '(', 43,
        ')', 44,
        '*', 27,
        '+', 25,
        ',', 12,
        '-', 26,
        '/', 28,
        '0', 19,
        ';', 16,
        '<', 34,
        '=', 31,
        '>', 33,
        '@', 9,
        '[', 45,
        ']', 46,
        '`', 11,
        '{', 47,
        '|', 3,
        '}', 48,
        '~', 39,
        '\t', 14,
        '\n', 14,
        '\r', 14,
        ' ', 14,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '&') ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '|') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(21);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead == '@') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA_AT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_whitespace);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__line_comment);
      if (lookahead == ';') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_dec_int);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == 'b') ADVANCE(4);
      if (lookahead == 'x') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_dec_int);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_bin_int);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_hex_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_POUNDt);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_POUNDf);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(38);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == 'f') ADVANCE(24);
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_base_symbol);
      if (set_contains(sym_base_symbol_character_set_1, 11, lookahead)) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_nil);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_base_symbol] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COMMA_AT] = ACTIONS(1),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(1),
    [sym_dec_int] = ACTIONS(1),
    [sym_bin_int] = ACTIONS(1),
    [sym_hex_int] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_POUNDt] = ACTIONS(1),
    [anon_sym_POUNDf] = ACTIONS(1),
    [anon_sym_nil] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(31),
    [sym_sexpr] = STATE(7),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [aux_sym_program_repeat1] = STATE(7),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
  },
  [2] = {
    [sym_sexpr] = STATE(2),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_base_symbol] = ACTIONS(43),
    [anon_sym_SQUOTE] = ACTIONS(46),
    [anon_sym_BQUOTE] = ACTIONS(49),
    [anon_sym_COMMA] = ACTIONS(52),
    [anon_sym_COMMA_AT] = ACTIONS(55),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(58),
    [sym_dec_int] = ACTIONS(61),
    [sym_bin_int] = ACTIONS(64),
    [sym_hex_int] = ACTIONS(64),
    [anon_sym_true] = ACTIONS(67),
    [anon_sym_false] = ACTIONS(67),
    [anon_sym_POUNDt] = ACTIONS(70),
    [anon_sym_POUNDf] = ACTIONS(70),
    [anon_sym_nil] = ACTIONS(67),
    [anon_sym_PLUS] = ACTIONS(73),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_STAR] = ACTIONS(73),
    [anon_sym_SLASH] = ACTIONS(76),
    [anon_sym_AMP_AMP] = ACTIONS(76),
    [anon_sym_PIPE_PIPE] = ACTIONS(76),
    [anon_sym_EQ] = ACTIONS(76),
    [anon_sym_BANG_EQ] = ACTIONS(76),
    [anon_sym_GT] = ACTIONS(73),
    [anon_sym_LT] = ACTIONS(73),
    [anon_sym_GT_EQ] = ACTIONS(76),
    [anon_sym_LT_EQ] = ACTIONS(76),
    [anon_sym_BANG] = ACTIONS(73),
    [anon_sym_STAR_STAR] = ACTIONS(76),
    [anon_sym_TILDE] = ACTIONS(79),
    [anon_sym_POUND] = ACTIONS(82),
    [sym_string] = ACTIONS(58),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(88),
    [anon_sym_RBRACK] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(91),
    [anon_sym_RBRACE] = ACTIONS(41),
  },
  [3] = {
    [sym_sexpr] = STATE(2),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [aux_sym_program_repeat1] = STATE(2),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(94),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(94),
    [anon_sym_LBRACE] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(94),
  },
  [4] = {
    [sym_sexpr] = STATE(3),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [sym_sexpr_list] = STATE(34),
    [aux_sym_program_repeat1] = STATE(3),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
    [anon_sym_RBRACE] = ACTIONS(96),
  },
  [5] = {
    [sym_sexpr] = STATE(3),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [sym_sexpr_list] = STATE(32),
    [aux_sym_program_repeat1] = STATE(3),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(96),
    [anon_sym_LBRACE] = ACTIONS(39),
  },
  [6] = {
    [sym_sexpr] = STATE(3),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [sym_sexpr_list] = STATE(33),
    [aux_sym_program_repeat1] = STATE(3),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
  },
  [7] = {
    [sym_sexpr] = STATE(2),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(98),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
  },
  [8] = {
    [sym_sexpr] = STATE(22),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
  },
  [9] = {
    [sym_sexpr] = STATE(21),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
  },
  [10] = {
    [sym_sexpr] = STATE(23),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
  },
  [11] = {
    [sym_sexpr] = STATE(26),
    [sym_timed_atom] = STATE(20),
    [sym_quoted] = STATE(20),
    [sym_quasiquoted] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_unquote_splice] = STATE(20),
    [sym_atom] = STATE(17),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(20),
    [sym_base_symbol] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_COMMA_AT] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(100),
    [sym_base_symbol] = ACTIONS(102),
    [anon_sym_AT] = ACTIONS(100),
    [anon_sym_SQUOTE] = ACTIONS(100),
    [anon_sym_BQUOTE] = ACTIONS(100),
    [anon_sym_COMMA] = ACTIONS(102),
    [anon_sym_COMMA_AT] = ACTIONS(100),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(100),
    [sym_dec_int] = ACTIONS(102),
    [sym_bin_int] = ACTIONS(100),
    [sym_hex_int] = ACTIONS(100),
    [anon_sym_true] = ACTIONS(102),
    [anon_sym_false] = ACTIONS(102),
    [anon_sym_POUNDt] = ACTIONS(100),
    [anon_sym_POUNDf] = ACTIONS(100),
    [anon_sym_nil] = ACTIONS(102),
    [anon_sym_PLUS] = ACTIONS(102),
    [anon_sym_DASH] = ACTIONS(102),
    [anon_sym_STAR] = ACTIONS(102),
    [anon_sym_SLASH] = ACTIONS(100),
    [anon_sym_AMP_AMP] = ACTIONS(100),
    [anon_sym_PIPE_PIPE] = ACTIONS(100),
    [anon_sym_EQ] = ACTIONS(100),
    [anon_sym_BANG_EQ] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LT] = ACTIONS(102),
    [anon_sym_GT_EQ] = ACTIONS(100),
    [anon_sym_LT_EQ] = ACTIONS(100),
    [anon_sym_BANG] = ACTIONS(102),
    [anon_sym_STAR_STAR] = ACTIONS(100),
    [anon_sym_TILDE] = ACTIONS(100),
    [anon_sym_POUND] = ACTIONS(102),
    [sym_string] = ACTIONS(100),
    [anon_sym_LPAREN] = ACTIONS(100),
    [anon_sym_RPAREN] = ACTIONS(100),
    [anon_sym_LBRACK] = ACTIONS(100),
    [anon_sym_RBRACK] = ACTIONS(100),
    [anon_sym_LBRACE] = ACTIONS(100),
    [anon_sym_RBRACE] = ACTIONS(100),
  },
  [13] = {
    [ts_builtin_sym_end] = ACTIONS(104),
    [sym_base_symbol] = ACTIONS(106),
    [anon_sym_AT] = ACTIONS(104),
    [anon_sym_SQUOTE] = ACTIONS(104),
    [anon_sym_BQUOTE] = ACTIONS(104),
    [anon_sym_COMMA] = ACTIONS(106),
    [anon_sym_COMMA_AT] = ACTIONS(104),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(104),
    [sym_dec_int] = ACTIONS(106),
    [sym_bin_int] = ACTIONS(104),
    [sym_hex_int] = ACTIONS(104),
    [anon_sym_true] = ACTIONS(106),
    [anon_sym_false] = ACTIONS(106),
    [anon_sym_POUNDt] = ACTIONS(104),
    [anon_sym_POUNDf] = ACTIONS(104),
    [anon_sym_nil] = ACTIONS(106),
    [anon_sym_PLUS] = ACTIONS(106),
    [anon_sym_DASH] = ACTIONS(106),
    [anon_sym_STAR] = ACTIONS(106),
    [anon_sym_SLASH] = ACTIONS(104),
    [anon_sym_AMP_AMP] = ACTIONS(104),
    [anon_sym_PIPE_PIPE] = ACTIONS(104),
    [anon_sym_EQ] = ACTIONS(104),
    [anon_sym_BANG_EQ] = ACTIONS(104),
    [anon_sym_GT] = ACTIONS(106),
    [anon_sym_LT] = ACTIONS(106),
    [anon_sym_GT_EQ] = ACTIONS(104),
    [anon_sym_LT_EQ] = ACTIONS(104),
    [anon_sym_BANG] = ACTIONS(106),
    [anon_sym_STAR_STAR] = ACTIONS(104),
    [anon_sym_TILDE] = ACTIONS(104),
    [anon_sym_POUND] = ACTIONS(106),
    [sym_string] = ACTIONS(104),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(104),
    [anon_sym_RBRACK] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(104),
    [anon_sym_RBRACE] = ACTIONS(104),
  },
  [14] = {
    [ts_builtin_sym_end] = ACTIONS(108),
    [sym_base_symbol] = ACTIONS(110),
    [anon_sym_AT] = ACTIONS(108),
    [anon_sym_SQUOTE] = ACTIONS(108),
    [anon_sym_BQUOTE] = ACTIONS(108),
    [anon_sym_COMMA] = ACTIONS(110),
    [anon_sym_COMMA_AT] = ACTIONS(108),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(108),
    [sym_dec_int] = ACTIONS(110),
    [sym_bin_int] = ACTIONS(108),
    [sym_hex_int] = ACTIONS(108),
    [anon_sym_true] = ACTIONS(110),
    [anon_sym_false] = ACTIONS(110),
    [anon_sym_POUNDt] = ACTIONS(108),
    [anon_sym_POUNDf] = ACTIONS(108),
    [anon_sym_nil] = ACTIONS(110),
    [anon_sym_PLUS] = ACTIONS(110),
    [anon_sym_DASH] = ACTIONS(110),
    [anon_sym_STAR] = ACTIONS(110),
    [anon_sym_SLASH] = ACTIONS(108),
    [anon_sym_AMP_AMP] = ACTIONS(108),
    [anon_sym_PIPE_PIPE] = ACTIONS(108),
    [anon_sym_EQ] = ACTIONS(108),
    [anon_sym_BANG_EQ] = ACTIONS(108),
    [anon_sym_GT] = ACTIONS(110),
    [anon_sym_LT] = ACTIONS(110),
    [anon_sym_GT_EQ] = ACTIONS(108),
    [anon_sym_LT_EQ] = ACTIONS(108),
    [anon_sym_BANG] = ACTIONS(110),
    [anon_sym_STAR_STAR] = ACTIONS(108),
    [anon_sym_TILDE] = ACTIONS(108),
    [anon_sym_POUND] = ACTIONS(110),
    [sym_string] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(108),
    [anon_sym_RPAREN] = ACTIONS(108),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(108),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(108),
  },
  [15] = {
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_base_symbol] = ACTIONS(114),
    [anon_sym_AT] = ACTIONS(112),
    [anon_sym_SQUOTE] = ACTIONS(112),
    [anon_sym_BQUOTE] = ACTIONS(112),
    [anon_sym_COMMA] = ACTIONS(114),
    [anon_sym_COMMA_AT] = ACTIONS(112),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(112),
    [sym_dec_int] = ACTIONS(114),
    [sym_bin_int] = ACTIONS(112),
    [sym_hex_int] = ACTIONS(112),
    [anon_sym_true] = ACTIONS(114),
    [anon_sym_false] = ACTIONS(114),
    [anon_sym_POUNDt] = ACTIONS(112),
    [anon_sym_POUNDf] = ACTIONS(112),
    [anon_sym_nil] = ACTIONS(114),
    [anon_sym_PLUS] = ACTIONS(114),
    [anon_sym_DASH] = ACTIONS(114),
    [anon_sym_STAR] = ACTIONS(114),
    [anon_sym_SLASH] = ACTIONS(112),
    [anon_sym_AMP_AMP] = ACTIONS(112),
    [anon_sym_PIPE_PIPE] = ACTIONS(112),
    [anon_sym_EQ] = ACTIONS(112),
    [anon_sym_BANG_EQ] = ACTIONS(112),
    [anon_sym_GT] = ACTIONS(114),
    [anon_sym_LT] = ACTIONS(114),
    [anon_sym_GT_EQ] = ACTIONS(112),
    [anon_sym_LT_EQ] = ACTIONS(112),
    [anon_sym_BANG] = ACTIONS(114),
    [anon_sym_STAR_STAR] = ACTIONS(112),
    [anon_sym_TILDE] = ACTIONS(112),
    [anon_sym_POUND] = ACTIONS(114),
    [sym_string] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(112),
    [anon_sym_RBRACK] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_RBRACE] = ACTIONS(112),
  },
  [16] = {
    [ts_builtin_sym_end] = ACTIONS(116),
    [sym_base_symbol] = ACTIONS(118),
    [anon_sym_AT] = ACTIONS(116),
    [anon_sym_SQUOTE] = ACTIONS(116),
    [anon_sym_BQUOTE] = ACTIONS(116),
    [anon_sym_COMMA] = ACTIONS(118),
    [anon_sym_COMMA_AT] = ACTIONS(116),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(116),
    [sym_dec_int] = ACTIONS(118),
    [sym_bin_int] = ACTIONS(116),
    [sym_hex_int] = ACTIONS(116),
    [anon_sym_true] = ACTIONS(118),
    [anon_sym_false] = ACTIONS(118),
    [anon_sym_POUNDt] = ACTIONS(116),
    [anon_sym_POUNDf] = ACTIONS(116),
    [anon_sym_nil] = ACTIONS(118),
    [anon_sym_PLUS] = ACTIONS(118),
    [anon_sym_DASH] = ACTIONS(118),
    [anon_sym_STAR] = ACTIONS(118),
    [anon_sym_SLASH] = ACTIONS(116),
    [anon_sym_AMP_AMP] = ACTIONS(116),
    [anon_sym_PIPE_PIPE] = ACTIONS(116),
    [anon_sym_EQ] = ACTIONS(116),
    [anon_sym_BANG_EQ] = ACTIONS(116),
    [anon_sym_GT] = ACTIONS(118),
    [anon_sym_LT] = ACTIONS(118),
    [anon_sym_GT_EQ] = ACTIONS(116),
    [anon_sym_LT_EQ] = ACTIONS(116),
    [anon_sym_BANG] = ACTIONS(118),
    [anon_sym_STAR_STAR] = ACTIONS(116),
    [anon_sym_TILDE] = ACTIONS(116),
    [anon_sym_POUND] = ACTIONS(118),
    [sym_string] = ACTIONS(116),
    [anon_sym_LPAREN] = ACTIONS(116),
    [anon_sym_RPAREN] = ACTIONS(116),
    [anon_sym_LBRACK] = ACTIONS(116),
    [anon_sym_RBRACK] = ACTIONS(116),
    [anon_sym_LBRACE] = ACTIONS(116),
    [anon_sym_RBRACE] = ACTIONS(116),
  },
  [17] = {
    [ts_builtin_sym_end] = ACTIONS(120),
    [sym_base_symbol] = ACTIONS(122),
    [anon_sym_AT] = ACTIONS(124),
    [anon_sym_SQUOTE] = ACTIONS(120),
    [anon_sym_BQUOTE] = ACTIONS(120),
    [anon_sym_COMMA] = ACTIONS(122),
    [anon_sym_COMMA_AT] = ACTIONS(120),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(120),
    [sym_dec_int] = ACTIONS(122),
    [sym_bin_int] = ACTIONS(120),
    [sym_hex_int] = ACTIONS(120),
    [anon_sym_true] = ACTIONS(122),
    [anon_sym_false] = ACTIONS(122),
    [anon_sym_POUNDt] = ACTIONS(120),
    [anon_sym_POUNDf] = ACTIONS(120),
    [anon_sym_nil] = ACTIONS(122),
    [anon_sym_PLUS] = ACTIONS(122),
    [anon_sym_DASH] = ACTIONS(122),
    [anon_sym_STAR] = ACTIONS(122),
    [anon_sym_SLASH] = ACTIONS(120),
    [anon_sym_AMP_AMP] = ACTIONS(120),
    [anon_sym_PIPE_PIPE] = ACTIONS(120),
    [anon_sym_EQ] = ACTIONS(120),
    [anon_sym_BANG_EQ] = ACTIONS(120),
    [anon_sym_GT] = ACTIONS(122),
    [anon_sym_LT] = ACTIONS(122),
    [anon_sym_GT_EQ] = ACTIONS(120),
    [anon_sym_LT_EQ] = ACTIONS(120),
    [anon_sym_BANG] = ACTIONS(122),
    [anon_sym_STAR_STAR] = ACTIONS(120),
    [anon_sym_TILDE] = ACTIONS(120),
    [anon_sym_POUND] = ACTIONS(122),
    [sym_string] = ACTIONS(120),
    [anon_sym_LPAREN] = ACTIONS(120),
    [anon_sym_RPAREN] = ACTIONS(120),
    [anon_sym_LBRACK] = ACTIONS(120),
    [anon_sym_RBRACK] = ACTIONS(120),
    [anon_sym_LBRACE] = ACTIONS(120),
    [anon_sym_RBRACE] = ACTIONS(120),
  },
  [18] = {
    [ts_builtin_sym_end] = ACTIONS(126),
    [sym_base_symbol] = ACTIONS(128),
    [anon_sym_AT] = ACTIONS(126),
    [anon_sym_SQUOTE] = ACTIONS(126),
    [anon_sym_BQUOTE] = ACTIONS(126),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_COMMA_AT] = ACTIONS(126),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(126),
    [sym_dec_int] = ACTIONS(128),
    [sym_bin_int] = ACTIONS(126),
    [sym_hex_int] = ACTIONS(126),
    [anon_sym_true] = ACTIONS(128),
    [anon_sym_false] = ACTIONS(128),
    [anon_sym_POUNDt] = ACTIONS(126),
    [anon_sym_POUNDf] = ACTIONS(126),
    [anon_sym_nil] = ACTIONS(128),
    [anon_sym_PLUS] = ACTIONS(128),
    [anon_sym_DASH] = ACTIONS(128),
    [anon_sym_STAR] = ACTIONS(128),
    [anon_sym_SLASH] = ACTIONS(126),
    [anon_sym_AMP_AMP] = ACTIONS(126),
    [anon_sym_PIPE_PIPE] = ACTIONS(126),
    [anon_sym_EQ] = ACTIONS(126),
    [anon_sym_BANG_EQ] = ACTIONS(126),
    [anon_sym_GT] = ACTIONS(128),
    [anon_sym_LT] = ACTIONS(128),
    [anon_sym_GT_EQ] = ACTIONS(126),
    [anon_sym_LT_EQ] = ACTIONS(126),
    [anon_sym_BANG] = ACTIONS(128),
    [anon_sym_STAR_STAR] = ACTIONS(126),
    [anon_sym_TILDE] = ACTIONS(126),
    [anon_sym_POUND] = ACTIONS(128),
    [sym_string] = ACTIONS(126),
    [anon_sym_LPAREN] = ACTIONS(126),
    [anon_sym_RPAREN] = ACTIONS(126),
    [anon_sym_LBRACK] = ACTIONS(126),
    [anon_sym_RBRACK] = ACTIONS(126),
    [anon_sym_LBRACE] = ACTIONS(126),
    [anon_sym_RBRACE] = ACTIONS(126),
  },
  [19] = {
    [ts_builtin_sym_end] = ACTIONS(130),
    [sym_base_symbol] = ACTIONS(132),
    [anon_sym_AT] = ACTIONS(130),
    [anon_sym_SQUOTE] = ACTIONS(130),
    [anon_sym_BQUOTE] = ACTIONS(130),
    [anon_sym_COMMA] = ACTIONS(132),
    [anon_sym_COMMA_AT] = ACTIONS(130),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(130),
    [sym_dec_int] = ACTIONS(132),
    [sym_bin_int] = ACTIONS(130),
    [sym_hex_int] = ACTIONS(130),
    [anon_sym_true] = ACTIONS(132),
    [anon_sym_false] = ACTIONS(132),
    [anon_sym_POUNDt] = ACTIONS(130),
    [anon_sym_POUNDf] = ACTIONS(130),
    [anon_sym_nil] = ACTIONS(132),
    [anon_sym_PLUS] = ACTIONS(132),
    [anon_sym_DASH] = ACTIONS(132),
    [anon_sym_STAR] = ACTIONS(132),
    [anon_sym_SLASH] = ACTIONS(130),
    [anon_sym_AMP_AMP] = ACTIONS(130),
    [anon_sym_PIPE_PIPE] = ACTIONS(130),
    [anon_sym_EQ] = ACTIONS(130),
    [anon_sym_BANG_EQ] = ACTIONS(130),
    [anon_sym_GT] = ACTIONS(132),
    [anon_sym_LT] = ACTIONS(132),
    [anon_sym_GT_EQ] = ACTIONS(130),
    [anon_sym_LT_EQ] = ACTIONS(130),
    [anon_sym_BANG] = ACTIONS(132),
    [anon_sym_STAR_STAR] = ACTIONS(130),
    [anon_sym_TILDE] = ACTIONS(130),
    [anon_sym_POUND] = ACTIONS(132),
    [sym_string] = ACTIONS(130),
    [anon_sym_LPAREN] = ACTIONS(130),
    [anon_sym_RPAREN] = ACTIONS(130),
    [anon_sym_LBRACK] = ACTIONS(130),
    [anon_sym_RBRACK] = ACTIONS(130),
    [anon_sym_LBRACE] = ACTIONS(130),
    [anon_sym_RBRACE] = ACTIONS(130),
  },
  [20] = {
    [ts_builtin_sym_end] = ACTIONS(120),
    [sym_base_symbol] = ACTIONS(122),
    [anon_sym_SQUOTE] = ACTIONS(120),
    [anon_sym_BQUOTE] = ACTIONS(120),
    [anon_sym_COMMA] = ACTIONS(122),
    [anon_sym_COMMA_AT] = ACTIONS(120),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(120),
    [sym_dec_int] = ACTIONS(122),
    [sym_bin_int] = ACTIONS(120),
    [sym_hex_int] = ACTIONS(120),
    [anon_sym_true] = ACTIONS(122),
    [anon_sym_false] = ACTIONS(122),
    [anon_sym_POUNDt] = ACTIONS(120),
    [anon_sym_POUNDf] = ACTIONS(120),
    [anon_sym_nil] = ACTIONS(122),
    [anon_sym_PLUS] = ACTIONS(122),
    [anon_sym_DASH] = ACTIONS(122),
    [anon_sym_STAR] = ACTIONS(122),
    [anon_sym_SLASH] = ACTIONS(120),
    [anon_sym_AMP_AMP] = ACTIONS(120),
    [anon_sym_PIPE_PIPE] = ACTIONS(120),
    [anon_sym_EQ] = ACTIONS(120),
    [anon_sym_BANG_EQ] = ACTIONS(120),
    [anon_sym_GT] = ACTIONS(122),
    [anon_sym_LT] = ACTIONS(122),
    [anon_sym_GT_EQ] = ACTIONS(120),
    [anon_sym_LT_EQ] = ACTIONS(120),
    [anon_sym_BANG] = ACTIONS(122),
    [anon_sym_STAR_STAR] = ACTIONS(120),
    [anon_sym_TILDE] = ACTIONS(120),
    [anon_sym_POUND] = ACTIONS(122),
    [sym_string] = ACTIONS(120),
    [anon_sym_LPAREN] = ACTIONS(120),
    [anon_sym_RPAREN] = ACTIONS(120),
    [anon_sym_LBRACK] = ACTIONS(120),
    [anon_sym_RBRACK] = ACTIONS(120),
    [anon_sym_LBRACE] = ACTIONS(120),
    [anon_sym_RBRACE] = ACTIONS(120),
  },
  [21] = {
    [ts_builtin_sym_end] = ACTIONS(134),
    [sym_base_symbol] = ACTIONS(136),
    [anon_sym_SQUOTE] = ACTIONS(134),
    [anon_sym_BQUOTE] = ACTIONS(134),
    [anon_sym_COMMA] = ACTIONS(136),
    [anon_sym_COMMA_AT] = ACTIONS(134),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(134),
    [sym_dec_int] = ACTIONS(136),
    [sym_bin_int] = ACTIONS(134),
    [sym_hex_int] = ACTIONS(134),
    [anon_sym_true] = ACTIONS(136),
    [anon_sym_false] = ACTIONS(136),
    [anon_sym_POUNDt] = ACTIONS(134),
    [anon_sym_POUNDf] = ACTIONS(134),
    [anon_sym_nil] = ACTIONS(136),
    [anon_sym_PLUS] = ACTIONS(136),
    [anon_sym_DASH] = ACTIONS(136),
    [anon_sym_STAR] = ACTIONS(136),
    [anon_sym_SLASH] = ACTIONS(134),
    [anon_sym_AMP_AMP] = ACTIONS(134),
    [anon_sym_PIPE_PIPE] = ACTIONS(134),
    [anon_sym_EQ] = ACTIONS(134),
    [anon_sym_BANG_EQ] = ACTIONS(134),
    [anon_sym_GT] = ACTIONS(136),
    [anon_sym_LT] = ACTIONS(136),
    [anon_sym_GT_EQ] = ACTIONS(134),
    [anon_sym_LT_EQ] = ACTIONS(134),
    [anon_sym_BANG] = ACTIONS(136),
    [anon_sym_STAR_STAR] = ACTIONS(134),
    [anon_sym_TILDE] = ACTIONS(134),
    [anon_sym_POUND] = ACTIONS(136),
    [sym_string] = ACTIONS(134),
    [anon_sym_LPAREN] = ACTIONS(134),
    [anon_sym_RPAREN] = ACTIONS(134),
    [anon_sym_LBRACK] = ACTIONS(134),
    [anon_sym_RBRACK] = ACTIONS(134),
    [anon_sym_LBRACE] = ACTIONS(134),
    [anon_sym_RBRACE] = ACTIONS(134),
  },
  [22] = {
    [ts_builtin_sym_end] = ACTIONS(138),
    [sym_base_symbol] = ACTIONS(140),
    [anon_sym_SQUOTE] = ACTIONS(138),
    [anon_sym_BQUOTE] = ACTIONS(138),
    [anon_sym_COMMA] = ACTIONS(140),
    [anon_sym_COMMA_AT] = ACTIONS(138),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(138),
    [sym_dec_int] = ACTIONS(140),
    [sym_bin_int] = ACTIONS(138),
    [sym_hex_int] = ACTIONS(138),
    [anon_sym_true] = ACTIONS(140),
    [anon_sym_false] = ACTIONS(140),
    [anon_sym_POUNDt] = ACTIONS(138),
    [anon_sym_POUNDf] = ACTIONS(138),
    [anon_sym_nil] = ACTIONS(140),
    [anon_sym_PLUS] = ACTIONS(140),
    [anon_sym_DASH] = ACTIONS(140),
    [anon_sym_STAR] = ACTIONS(140),
    [anon_sym_SLASH] = ACTIONS(138),
    [anon_sym_AMP_AMP] = ACTIONS(138),
    [anon_sym_PIPE_PIPE] = ACTIONS(138),
    [anon_sym_EQ] = ACTIONS(138),
    [anon_sym_BANG_EQ] = ACTIONS(138),
    [anon_sym_GT] = ACTIONS(140),
    [anon_sym_LT] = ACTIONS(140),
    [anon_sym_GT_EQ] = ACTIONS(138),
    [anon_sym_LT_EQ] = ACTIONS(138),
    [anon_sym_BANG] = ACTIONS(140),
    [anon_sym_STAR_STAR] = ACTIONS(138),
    [anon_sym_TILDE] = ACTIONS(138),
    [anon_sym_POUND] = ACTIONS(140),
    [sym_string] = ACTIONS(138),
    [anon_sym_LPAREN] = ACTIONS(138),
    [anon_sym_RPAREN] = ACTIONS(138),
    [anon_sym_LBRACK] = ACTIONS(138),
    [anon_sym_RBRACK] = ACTIONS(138),
    [anon_sym_LBRACE] = ACTIONS(138),
    [anon_sym_RBRACE] = ACTIONS(138),
  },
  [23] = {
    [ts_builtin_sym_end] = ACTIONS(142),
    [sym_base_symbol] = ACTIONS(144),
    [anon_sym_SQUOTE] = ACTIONS(142),
    [anon_sym_BQUOTE] = ACTIONS(142),
    [anon_sym_COMMA] = ACTIONS(144),
    [anon_sym_COMMA_AT] = ACTIONS(142),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(142),
    [sym_dec_int] = ACTIONS(144),
    [sym_bin_int] = ACTIONS(142),
    [sym_hex_int] = ACTIONS(142),
    [anon_sym_true] = ACTIONS(144),
    [anon_sym_false] = ACTIONS(144),
    [anon_sym_POUNDt] = ACTIONS(142),
    [anon_sym_POUNDf] = ACTIONS(142),
    [anon_sym_nil] = ACTIONS(144),
    [anon_sym_PLUS] = ACTIONS(144),
    [anon_sym_DASH] = ACTIONS(144),
    [anon_sym_STAR] = ACTIONS(144),
    [anon_sym_SLASH] = ACTIONS(142),
    [anon_sym_AMP_AMP] = ACTIONS(142),
    [anon_sym_PIPE_PIPE] = ACTIONS(142),
    [anon_sym_EQ] = ACTIONS(142),
    [anon_sym_BANG_EQ] = ACTIONS(142),
    [anon_sym_GT] = ACTIONS(144),
    [anon_sym_LT] = ACTIONS(144),
    [anon_sym_GT_EQ] = ACTIONS(142),
    [anon_sym_LT_EQ] = ACTIONS(142),
    [anon_sym_BANG] = ACTIONS(144),
    [anon_sym_STAR_STAR] = ACTIONS(142),
    [anon_sym_TILDE] = ACTIONS(142),
    [anon_sym_POUND] = ACTIONS(144),
    [sym_string] = ACTIONS(142),
    [anon_sym_LPAREN] = ACTIONS(142),
    [anon_sym_RPAREN] = ACTIONS(142),
    [anon_sym_LBRACK] = ACTIONS(142),
    [anon_sym_RBRACK] = ACTIONS(142),
    [anon_sym_LBRACE] = ACTIONS(142),
    [anon_sym_RBRACE] = ACTIONS(142),
  },
  [24] = {
    [ts_builtin_sym_end] = ACTIONS(146),
    [sym_base_symbol] = ACTIONS(148),
    [anon_sym_SQUOTE] = ACTIONS(146),
    [anon_sym_BQUOTE] = ACTIONS(146),
    [anon_sym_COMMA] = ACTIONS(148),
    [anon_sym_COMMA_AT] = ACTIONS(146),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(146),
    [sym_dec_int] = ACTIONS(148),
    [sym_bin_int] = ACTIONS(146),
    [sym_hex_int] = ACTIONS(146),
    [anon_sym_true] = ACTIONS(148),
    [anon_sym_false] = ACTIONS(148),
    [anon_sym_POUNDt] = ACTIONS(146),
    [anon_sym_POUNDf] = ACTIONS(146),
    [anon_sym_nil] = ACTIONS(148),
    [anon_sym_PLUS] = ACTIONS(148),
    [anon_sym_DASH] = ACTIONS(148),
    [anon_sym_STAR] = ACTIONS(148),
    [anon_sym_SLASH] = ACTIONS(146),
    [anon_sym_AMP_AMP] = ACTIONS(146),
    [anon_sym_PIPE_PIPE] = ACTIONS(146),
    [anon_sym_EQ] = ACTIONS(146),
    [anon_sym_BANG_EQ] = ACTIONS(146),
    [anon_sym_GT] = ACTIONS(148),
    [anon_sym_LT] = ACTIONS(148),
    [anon_sym_GT_EQ] = ACTIONS(146),
    [anon_sym_LT_EQ] = ACTIONS(146),
    [anon_sym_BANG] = ACTIONS(148),
    [anon_sym_STAR_STAR] = ACTIONS(146),
    [anon_sym_TILDE] = ACTIONS(146),
    [anon_sym_POUND] = ACTIONS(148),
    [sym_string] = ACTIONS(146),
    [anon_sym_LPAREN] = ACTIONS(146),
    [anon_sym_RPAREN] = ACTIONS(146),
    [anon_sym_LBRACK] = ACTIONS(146),
    [anon_sym_RBRACK] = ACTIONS(146),
    [anon_sym_LBRACE] = ACTIONS(146),
    [anon_sym_RBRACE] = ACTIONS(146),
  },
  [25] = {
    [sym_atom] = STATE(28),
    [sym_int] = STATE(15),
    [sym_bool] = STATE(15),
    [sym_operator] = STATE(15),
    [sym_symbol] = STATE(15),
    [sym_scoped_symbol] = STATE(13),
    [sym_grouped_symbol] = STATE(13),
    [sym_list] = STATE(28),
    [sym_base_symbol] = ACTIONS(7),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(17),
    [sym_dec_int] = ACTIONS(19),
    [sym_bin_int] = ACTIONS(21),
    [sym_hex_int] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_POUNDt] = ACTIONS(25),
    [anon_sym_POUNDf] = ACTIONS(25),
    [anon_sym_nil] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [sym_string] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
  },
  [26] = {
    [ts_builtin_sym_end] = ACTIONS(150),
    [sym_base_symbol] = ACTIONS(152),
    [anon_sym_SQUOTE] = ACTIONS(150),
    [anon_sym_BQUOTE] = ACTIONS(150),
    [anon_sym_COMMA] = ACTIONS(152),
    [anon_sym_COMMA_AT] = ACTIONS(150),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(150),
    [sym_dec_int] = ACTIONS(152),
    [sym_bin_int] = ACTIONS(150),
    [sym_hex_int] = ACTIONS(150),
    [anon_sym_true] = ACTIONS(152),
    [anon_sym_false] = ACTIONS(152),
    [anon_sym_POUNDt] = ACTIONS(150),
    [anon_sym_POUNDf] = ACTIONS(150),
    [anon_sym_nil] = ACTIONS(152),
    [anon_sym_PLUS] = ACTIONS(152),
    [anon_sym_DASH] = ACTIONS(152),
    [anon_sym_STAR] = ACTIONS(152),
    [anon_sym_SLASH] = ACTIONS(150),
    [anon_sym_AMP_AMP] = ACTIONS(150),
    [anon_sym_PIPE_PIPE] = ACTIONS(150),
    [anon_sym_EQ] = ACTIONS(150),
    [anon_sym_BANG_EQ] = ACTIONS(150),
    [anon_sym_GT] = ACTIONS(152),
    [anon_sym_LT] = ACTIONS(152),
    [anon_sym_GT_EQ] = ACTIONS(150),
    [anon_sym_LT_EQ] = ACTIONS(150),
    [anon_sym_BANG] = ACTIONS(152),
    [anon_sym_STAR_STAR] = ACTIONS(150),
    [anon_sym_TILDE] = ACTIONS(150),
    [anon_sym_POUND] = ACTIONS(152),
    [sym_string] = ACTIONS(150),
    [anon_sym_LPAREN] = ACTIONS(150),
    [anon_sym_RPAREN] = ACTIONS(150),
    [anon_sym_LBRACK] = ACTIONS(150),
    [anon_sym_RBRACK] = ACTIONS(150),
    [anon_sym_LBRACE] = ACTIONS(150),
    [anon_sym_RBRACE] = ACTIONS(150),
  },
  [27] = {
    [ts_builtin_sym_end] = ACTIONS(154),
    [sym_base_symbol] = ACTIONS(156),
    [anon_sym_SQUOTE] = ACTIONS(154),
    [anon_sym_BQUOTE] = ACTIONS(154),
    [anon_sym_COMMA] = ACTIONS(156),
    [anon_sym_COMMA_AT] = ACTIONS(154),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(154),
    [sym_dec_int] = ACTIONS(156),
    [sym_bin_int] = ACTIONS(154),
    [sym_hex_int] = ACTIONS(154),
    [anon_sym_true] = ACTIONS(156),
    [anon_sym_false] = ACTIONS(156),
    [anon_sym_POUNDt] = ACTIONS(154),
    [anon_sym_POUNDf] = ACTIONS(154),
    [anon_sym_nil] = ACTIONS(156),
    [anon_sym_PLUS] = ACTIONS(156),
    [anon_sym_DASH] = ACTIONS(156),
    [anon_sym_STAR] = ACTIONS(156),
    [anon_sym_SLASH] = ACTIONS(154),
    [anon_sym_AMP_AMP] = ACTIONS(154),
    [anon_sym_PIPE_PIPE] = ACTIONS(154),
    [anon_sym_EQ] = ACTIONS(154),
    [anon_sym_BANG_EQ] = ACTIONS(154),
    [anon_sym_GT] = ACTIONS(156),
    [anon_sym_LT] = ACTIONS(156),
    [anon_sym_GT_EQ] = ACTIONS(154),
    [anon_sym_LT_EQ] = ACTIONS(154),
    [anon_sym_BANG] = ACTIONS(156),
    [anon_sym_STAR_STAR] = ACTIONS(154),
    [anon_sym_TILDE] = ACTIONS(154),
    [anon_sym_POUND] = ACTIONS(156),
    [sym_string] = ACTIONS(154),
    [anon_sym_LPAREN] = ACTIONS(154),
    [anon_sym_RPAREN] = ACTIONS(154),
    [anon_sym_LBRACK] = ACTIONS(154),
    [anon_sym_RBRACK] = ACTIONS(154),
    [anon_sym_LBRACE] = ACTIONS(154),
    [anon_sym_RBRACE] = ACTIONS(154),
  },
  [28] = {
    [ts_builtin_sym_end] = ACTIONS(158),
    [sym_base_symbol] = ACTIONS(160),
    [anon_sym_SQUOTE] = ACTIONS(158),
    [anon_sym_BQUOTE] = ACTIONS(158),
    [anon_sym_COMMA] = ACTIONS(160),
    [anon_sym_COMMA_AT] = ACTIONS(158),
    [sym_whitespace] = ACTIONS(3),
    [sym__comment] = ACTIONS(3),
    [sym__line_comment] = ACTIONS(5),
    [sym_float] = ACTIONS(158),
    [sym_dec_int] = ACTIONS(160),
    [sym_bin_int] = ACTIONS(158),
    [sym_hex_int] = ACTIONS(158),
    [anon_sym_true] = ACTIONS(160),
    [anon_sym_false] = ACTIONS(160),
    [anon_sym_POUNDt] = ACTIONS(158),
    [anon_sym_POUNDf] = ACTIONS(158),
    [anon_sym_nil] = ACTIONS(160),
    [anon_sym_PLUS] = ACTIONS(160),
    [anon_sym_DASH] = ACTIONS(160),
    [anon_sym_STAR] = ACTIONS(160),
    [anon_sym_SLASH] = ACTIONS(158),
    [anon_sym_AMP_AMP] = ACTIONS(158),
    [anon_sym_PIPE_PIPE] = ACTIONS(158),
    [anon_sym_EQ] = ACTIONS(158),
    [anon_sym_BANG_EQ] = ACTIONS(158),
    [anon_sym_GT] = ACTIONS(160),
    [anon_sym_LT] = ACTIONS(160),
    [anon_sym_GT_EQ] = ACTIONS(158),
    [anon_sym_LT_EQ] = ACTIONS(158),
    [anon_sym_BANG] = ACTIONS(160),
    [anon_sym_STAR_STAR] = ACTIONS(158),
    [anon_sym_TILDE] = ACTIONS(158),
    [anon_sym_POUND] = ACTIONS(160),
    [sym_string] = ACTIONS(158),
    [anon_sym_LPAREN] = ACTIONS(158),
    [anon_sym_RPAREN] = ACTIONS(158),
    [anon_sym_LBRACK] = ACTIONS(158),
    [anon_sym_RBRACK] = ACTIONS(158),
    [anon_sym_LBRACE] = ACTIONS(158),
    [anon_sym_RBRACE] = ACTIONS(158),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(5), 1,
      sym__line_comment,
    ACTIONS(162), 1,
      sym_base_symbol,
    ACTIONS(3), 2,
      sym_whitespace,
      sym__comment,
  [11] = 3,
    ACTIONS(5), 1,
      sym__line_comment,
    ACTIONS(164), 1,
      sym_base_symbol,
    ACTIONS(3), 2,
      sym_whitespace,
      sym__comment,
  [22] = 3,
    ACTIONS(5), 1,
      sym__line_comment,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_whitespace,
      sym__comment,
  [33] = 3,
    ACTIONS(5), 1,
      sym__line_comment,
    ACTIONS(168), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_whitespace,
      sym__comment,
  [44] = 3,
    ACTIONS(5), 1,
      sym__line_comment,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_whitespace,
      sym__comment,
  [55] = 3,
    ACTIONS(5), 1,
      sym__line_comment,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_whitespace,
      sym__comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(29)] = 0,
  [SMALL_STATE(30)] = 11,
  [SMALL_STATE(31)] = 22,
  [SMALL_STATE(32)] = 33,
  [SMALL_STATE(33)] = 44,
  [SMALL_STATE(34)] = 55,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexpr_list, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexpr, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexpr, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_symbol, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_symbol, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scoped_symbol, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scoped_symbol, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote_splice, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote_splice, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quasiquoted, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quasiquoted, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timed_atom, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_timed_atom, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [166] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wal(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_base_symbol,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
